### ISSUE TITLE
是公司的产品吗

### ISSUE THREAD

**Issue by bigide-ai** [open-botech/ClickCat#2]
后端会开源吗，看到还有vue分支

**Comment by wangqinghuan** [comment]
1、使用到的后端都会开源。
2、vue3是正在重构的版本，后面用vue3+ts。

**Comment by bigide-ai** [comment]
后端用什么语言写的

**Comment by wangqinghuan** [comment]
> 后端用什么语言写的

Python https://github.com/open-botech/machine-learning-as-rest
